name 'nginx-revprox'
maintainer 'Ruben Boonen (b33f)'
maintainer_email 'ru.boonen@gmail.com'
license 'Apache-2.0'
description 'Simple Chef test, nginx static & rev proxy'
version '0.1.0'
chef_version '>= 14.0'